CFLAGS=-I.. --std=gnu99 -Wall
LDFLAGS=../cresus_ex.a -lm

TARGET=	cresus_xx #\
	cresus_zz

OBJ=	cresus_xx.o #\
	cresus_zz.o 

all: $(TARGET)

debug: CFLAGS+=-O0 -g
debug: all

cresus_%: cresus_%.o
	$(CC) $(CFLAGS) $< -o $@ $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(TARGET) $(OBJ)
